#!/usr/bin/env bash
# OpenRecall one-command deploy: detect the hardware, pick a profile, start it.
#
#   ./deploy/deploy.sh              # detect, write .env if absent, start
#   ./deploy/deploy.sh --detect     # print what it would choose, change nothing
#   ./deploy/deploy.sh --force      # overwrite an existing .env
#   ./deploy/deploy.sh --profile X  # override detection (apple|nvidia|cpu|cloud)
#
# Generation is idempotent: an existing .env is never overwritten without
# --force, because it holds the operator's endpoints and model choices and
# clobbering it silently would be worse than doing nothing.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/deploy/.env"
COMPOSE_FILE="$REPO_ROOT/deploy/docker-compose.yml"

FORCE=0
DETECT_ONLY=0
PROFILE_OVERRIDE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --force)   FORCE=1 ;;
        --detect)  DETECT_ONLY=1 ;;
        --profile) PROFILE_OVERRIDE="${2:-}"; shift ;;
        -h|--help) sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

# --- Container runtime -------------------------------------------------------
detect_runtime() {
    if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
        echo "docker"
    elif command -v podman >/dev/null 2>&1; then
        echo "podman"
    else
        echo "none"
    fi
}

# --- Hardware ----------------------------------------------------------------
# Order matters: check for a usable GPU before falling back to CPU, and treat
# Apple Silicon specially because a container there cannot reach Metal.
detect_profile() {
    local os arch
    os="$(uname -s)"
    arch="$(uname -m)"

    if [ "$os" = "Darwin" ] && [ "$arch" = "arm64" ]; then
        echo "apple"; return
    fi
    # nvidia-smi present AND actually able to talk to a driver. The binary
    # alone is not enough: it ships in images with no device attached.
    if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
        echo "nvidia"; return
    fi
    echo "cpu"
}

RUNTIME="$(detect_runtime)"
PROFILE="${PROFILE_OVERRIDE:-$(detect_profile)}"

echo "detected:"
echo "  os/arch          : $(uname -s)/$(uname -m)"
echo "  container runtime: $RUNTIME"
echo "  profile          : $PROFILE${PROFILE_OVERRIDE:+ (overridden)}"

case "$PROFILE" in
    apple)
        INFERENCE_URL="http://host.docker.internal:8767"
        OLLAMA_HOST="http://host.docker.internal:11434/v1"
        echo "  inference        : NATIVE host process (Docker on macOS has no Metal access)"
        ;;
    nvidia)
        INFERENCE_URL="http://inference:8767"
        OLLAMA_HOST="http://ollama:11434/v1"
        echo "  inference        : CUDA container"
        echo
        echo "NOT YET IMPLEMENTED. The ASR backend is ready (faster-whisper takes"
        echo "OPENRECALL_FASTER_WHISPER_DEVICE=cuda), but three things are missing:"
        echo "a CUDA base image for deploy/Dockerfile.inference, GPU device"
        echo "reservation + an Ollama service in compose, and a VRAM budget measured"
        echo "on the actual card. See the containerized-deployment design, P3."
        echo "Detection works; the profile does not."
        exit 1
        ;;
    cpu)
        INFERENCE_URL="http://inference:8767"
        # No Ollama container is started here, so point at the host's.
        OLLAMA_HOST="http://host.docker.internal:11434/v1"
        echo "  inference        : CPU container (faster-whisper small.en, ~3.5x realtime)"
        ;;
    cloud)
        INFERENCE_URL=""
        OLLAMA_HOST=""
        echo "  inference        : cloud endpoints (nothing local started)"
        ;;
    *)
        echo "unknown profile: $PROFILE" >&2; exit 2 ;;
esac

if [ "$RUNTIME" = "none" ]; then
    echo
    echo "No container runtime found. Install Docker Desktop (macOS) or docker/podman (Linux)."
    exit 1
fi

if [ "$DETECT_ONLY" = "1" ]; then
    echo
    echo "(--detect: nothing written, nothing started)"
    exit 0
fi

# --- .env generation (idempotent) -------------------------------------------
if [ -e "$ENV_FILE" ] && [ "$FORCE" != "1" ]; then
    echo
    echo "$ENV_FILE already exists — leaving it alone."
    echo "It holds your endpoints and model choices; pass --force to regenerate."
else
    umask 077          # endpoints and, later, possibly keys
    cat > "$ENV_FILE" <<EOF
# Generated by deploy/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) for profile: $PROFILE
# Edit freely — this file is never overwritten without --force.

# Match the data volume's owner. Secret creation on first boot is not guarded
# against PermissionError, so a mismatch aborts the container.
OPENRECALL_UID=$(id -u)
OPENRECALL_GID=$(id -g)

# Where the recordings live. Back this up (see deploy/README.md).
OPENRECALL_DATA=./data

# Where ASR and speaker embedding run.
OPENRECALL_INFERENCE_URL=$INFERENCE_URL

# LLM endpoints. These default to localhost in code, which inside a container
# is the container itself, and extraction then fails silently.
OPENRECALL_LLM_BASE_URL=$OLLAMA_HOST
OPENRECALL_EMBED_BASE_URL=$OLLAMA_HOST
OPENRECALL_VLM_BASE_URL=$OLLAMA_HOST

# Model names have no defaults in code; boot aborts without them.
OPENRECALL_EMBED_MODEL=nomic-embed-text
OPENRECALL_LLM_MODEL=qwen2.5:7b
# OPENRECALL_VLM_MODEL is optional — unset disables vision cleanly.
EOF
    echo
    echo "wrote $ENV_FILE"
fi

# --- Start -------------------------------------------------------------------
echo
if [ "$PROFILE" = "apple" ]; then
    # The honest limit: "one command" does not cover the native sidecar.
    if ! curl -fsS --max-time 2 http://127.0.0.1:8767/info >/dev/null 2>&1; then
        echo "The inference sidecar is not running. On this profile it runs NATIVELY,"
        echo "because a container on macOS cannot reach Metal. Start it first, in"
        echo "another terminal:"
        echo
        echo "    cd $REPO_ROOT/server"
        echo "    python -u scripts/run_inference.py --host 0.0.0.0 --port 8767"
        echo
        echo "(--host 0.0.0.0 matters: the default 127.0.0.1 is not reachable from"
        echo " inside the container.)"
        echo
        echo "Then re-run this script."
        exit 1
    fi
    echo "inference sidecar: reachable on :8767"
fi

# The cpu profile also brings up the inference container; apple does not,
# because its sidecar is the native process checked above.
COMPOSE_PROFILE_ARGS=()
if [ "$PROFILE" = "cpu" ]; then
    COMPOSE_PROFILE_ARGS=(--profile cpu)
    echo "starting the core and the CPU inference container…"
    echo "(first run downloads the ASR model into a named volume — allow a few minutes)"
else
    echo "starting the core…"
fi
$RUNTIME compose --env-file "$ENV_FILE" "${COMPOSE_PROFILE_ARGS[@]}" -f "$COMPOSE_FILE" up -d --build

echo
echo "up. Follow the log for the bearer token and signing key:"
echo "    $RUNTIME compose -f $COMPOSE_FILE logs -f core"
